### ISSUE TITLE
Zoznam odbernych miest

### ISSUE THREAD

**Issue by robkog** [psekan/somvrade#14]
Dobry deň, prosim Vás kedy sa bude aktualizovať databaza odbernych miest ? Pevne verím,že sa nahlásilo ich mnoho no v ponuke miest včera bola Žilina a dnes je to len Lipt. Mikuláš. 
Myslím si, že ak sa nahodia všetky miesta ktore momentalne mate nahlasené tak sa aspoň bude vidieť, že kde a čo chýba... preto dufam, že sa tak stane čo najskôr... 🙂  držím Vám palce

**Comment by mesiarm** [comment]
Podľa kódu je tam doplnené schvaľovanie. Asi by však bolo dobré doplniť do api možnosť kontrolovať, či dané miesto nečaká na schválenie a nedovoliť vložiť rovnaké, aby nevznikali duplicity a prípadne zobraziť chybovú hlášku.
