### ISSUE TITLE
REST API - Android app-ka

### ISSUE THREAD

**Issue by ghost** [psekan/somvrade#15]
caute,

az by ste chceli, mohol by som pripravit aj android appku, pokial by bolo dodane REST API z vasej strany...
pre zaciatok by uplne stacil nahlad danych odbernych miest s poctom nahlasenych ludi v rade...
podla mna by nemalo zmysel cez appku pridavat odberne miesta..
EDIT: samozrejme aj nahlasovanie...
akurat sa obavam ze ludia budu tam davat hovadiny :(

kazdopadne, pri dnesnom googli, by asi schvalenie app trvalo aj 2-3 dni :(

dajte mi vediet :)

diky

**Comment by thebrownfox** [comment]
Ja to vidim tu. IMHO android aplikacia je zbytocna. 
https://github.com/psekan/somvrade/blob/main/api/routes/web.php

**Comment by ghost** [comment]
ah pravda, je to tam :)...asi mas pravdu s tou zbytocnostou, ale minimalne to skusit mozem (uz som s tym aj zacal)...ak s tym budu suhlasit...

**Comment by ghost** [comment]
no, uz to aj tak nestiham do testovania, tak aspon nech ludia pouzivaju ten web :) alebo ak sa najde niekto odhodlany s tym daco robit :D ... mozte tuto "issue" kludne zavriet :)

**Comment by dmatis2** [comment]
Tak mozno premapovat do React-Native by slo, ale zas neviem ci by to ludia stahovali uz dnes teda. U nas v KE myslim nejak nad 100 miest. Verim, ze ludia tam daju nejaku info
