### ISSUE TITLE
rozlisit a zobrazit vsetky stanoviska na tom istom odbernom mieste

### ISSUE THREAD

**Issue by mzatko** [psekan/somvrade#19]
caute, good work!
Iba navrh: asi by bolo vhodne, ak je to mozne, nejak rozlisit tych viacej stanovisk na jednom odbernom mieste, aj ked asi nikto nevie, ci budu nejak oznacovane a ako budu oznacovane. A potom pri vybere niektoreho stanoviska zobrazit vsetky stanoviska na tom istom mieste, tak by uzivatelia ziskali uzitocnejsiu informaciu.

**Comment by 4ndrej** [comment]
predpokladam ze vsetky stanoviska daneho miesta maju jeden spolocny rad
