### ISSUE TITLE
Snazim sa pridavat

### ISSUE THREAD

**Issue by mascot4m** [psekan/somvrade#7]
Pridal som zopar miest v Bratislave, ale nezobrazuju sa v zozname. Je to kvoli tomu vypadku a mam pokracovat v nahadzovani?

**Comment by psekan** [comment]
Momentálne je kvôli výkonu zrušené zobrazenie miest z databazy. Ak ste ich vložili a aplikácia vám ukázala, že pridane prebehlo správne, v databáze budú, ale aktuálne sa nezobrazia. Ku večeru budem migrovať aplikáciu na nový server a opäť sa budú zobrazovať všetky aktuálne pridané miesta.
